pipeline {
    agent any

    environment {
        NAMESPACE = "monitoring"
    }

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Deploy Monitoring Stack') {
            // Only run this if files in 'monitoring' folder changed
            when {
                changeset "infra/k8s/monitoring/**"
            }
            steps {
                script {
                    dir('infra/k8s/monitoring') {
                        withCredentials([string(credentialsId: 'SLACK_WEBHOOK_URL', variable: 'SLACK_URL')]) {
                            sh """
                                echo "Deploying Monitoring Stack..."
                                helm upgrade --install monitoring-stack prometheus-community/kube-prometheus-stack \
                                  --namespace ${NAMESPACE} \
                                  --create-namespace \
                                  -f values.yaml \
                                  -f values-dev.yaml \
                                  --set alertmanager.config.global.slack_api_url="${env.SLACK_URL}" \
                                  --wait
                            """
                        }
                    } // FIX 2: Closing brace for dir
                }
            }
        }
    }

    post {
        success {
            echo "✅ Monitoring Configuration Updated Successfully"
        }
    }
}